apiVersion: apps/v1
kind: Deployment
metadata:
  name: singtest
#  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singtest
  template:
    metadata:
      labels:
        app: singtest
    spec:
      containers:
        - name: singtest
          image: muoubenben/singtest:latest
          imagePullPolicy: IfNotPresent   # already in the sample
          # image: muoubenben/singtest:latest  # Replace with your real image
          # imagePullPolicy: Never
          ports:
            - containerPort: 8090
